### ISSUE TITLE
Add support for Curve geometry with srsName in HTTP URI format

### ISSUE THREAD

**Issue by keshavnangare** [opengeospatial/geomatics-geotk#6]
Reference from this issue: https://github.com/opengeospatial/ets-wfs20/issues/180#issue-729585186

The method `convertToMultiType(Node geomNode)` should be updated to support Curve geometry with srsName in HTTP URI format

**Comment by keshav-nangare** [comment]
We have updated the `convertToMultiType` method which will convert the Curve node to MultiCurve node structure along with srsName in URN format then it will pass for further execution to JTS method.

Fixed with this PR: #7.

**Comment by dstenger** [comment]
@keshav-nangare Please see my comment in the pull request.
